name: workflow-cargo-audit-on-schedule
run-name: cargo audit run by ${{ github.actor }}
on:
  schedule:
    - cron: "15 10 * * *"
jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
